spring.application.name=com.project.fitness_tracker

# PostgreSQL Database Configuration
# It is strongly recommended to use environment variables for database credentials.
# JDBC URL (Note the 'jdbc:' prefix added)

spring.datasource.password=${DB_PASSWORD:npg_0HpCaLqDy3NZ}
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-autumn-recipe-aizca8ap-pooler.c-4.us-east-1.aws.neon.tech/fitness}
spring.datasource.username=${DB_USERNAME:neondb_owner}

# Driver and Dialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: Helpful for debugging Hibernate/JPA issues
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update